# Generated by Django 4.1.6 on 2023-02-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('model', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)])),
                ('price', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('car_buy', models.ManyToManyField(to='board.car')),
            ],
        ),
    ]
